# permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 6
comments: false
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: Lucas Wilson-Richter
# description: "A free Jekyll theme"
email: blog@lucasrichter.id.au
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com"
url: "https://lucaswilric.github.io"
repository: "https://github.com/lucaswilric/lucaswilric.github.io"
# disqus_shortname: "fernandomoreira"
# google_analytics: UA-52446115-1

# social footer
social:
  github:
    slug: github
    link: http://github.com/lucaswilric
  #facebook:
    #slug: facebook
    #link: http://facebook.com/fernando.dev
  twitter:
    slug: twitter
    link: http://twitter.com/lucasrichter
  #instagram:
    #slug: instagram
    #link: http://instagram.com/nandomoreira.me
  #linkedin:
    #slug: linkedin
    #link: http://linkedin.com/in/nandomoreirame

gems:
  - jemoji
